### DISCUSSION TITLE
Method to use uv to install mineru 2.x with Python 3.13

### DISCUSSION THREAD

**Discussion by hongbo-miao** [magicpdf/Magic-PDF#1374] [Show and tell]
Just share a way to use [uv](https://github.com/astral-sh/uv) to install mineru 2.x with Python 3.13. Succeed in Ubuntu 24.

Hope it helps people save some time. ☺️

## 6/22/2025 (Current Method for mineru 2.x)

mineru 2.x simplified a lot, there is not difference when install compared to other libraries now.

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.13.0"
dependencies = [
  "mineru[core]==2.0.6",
]

[tool.uv]
package = false
required-version = ">=0.6.0"
```
Assume your PDFs are at `data` folder, you can run: `uv run mineru --path=data --output=output`

## 1/31/2025 (Old Method for magic-pdf 1.x)

<details>
  <summary>Click to expand</summary>

Just share a way to use [uv](https://github.com/astral-sh/uv) to install magic-pdf 1.x with Python 3.12. Succeed in Ubuntu 22.

**Notes:**

- `magic-pdf[full]` has a dependency `detectron2` which does not have wheel. Currently for uv to install package that needs `--no-build-isolation`, need run the command manually first, which is why we do `uv pip install --no-build-isolation git+https://github.com/facebookresearch/detectron2.git`.
- `detectron2` didn't define the dependency `torch` but requires it, which is why we manually run `uv pip install torch` before `detectron2`.
-  `magic-pdf[full]` currently is using a pre-release dependency `paddlepaddle` which is why we need `prerelease = "allow"`, but in future, once magic-pdf relies on a formal release version of `paddlepaddle`, then no need `prerelease = "allow"`.
- `paddlepaddle-gpu` has to install after `magic-pdf[full]`.

pyproject.toml

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.12.0"

[project.optional-dependencies]
build = [
  "setuptools",
  "torch",
]
compile = [
  "detectron2",
  "magic-pdf[full]==1.1.0",
]
paddlepaddle-gpu = [
  "paddlepaddle-gpu==3.0.0b2",
]

[tool.uv]
package = false
prerelease = "allow"
no-build-isolation-package = ["detectron2"]

[tool.uv.sources]
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "main" }
paddlepaddle-gpu = { index = "paddlepaddle-gpu" }

[[tool.uv.index]]
name = "paddlepaddle-gpu"
url = "https://www.paddlepaddle.org.cn/packages/stable/cu118"
explicit = true
```
Now just need install by

```sh
uv sync --extra=build
uv sync --extra=build --extra=compile
uv sync --extra=build --extra=compile --extra=paddlepaddle-gpu
```

Here is a full demo: https://github.com/hongbo-miao/hongbomiao.com/tree/main/machine-learning/mineru
Reference: https://docs.astral.sh/uv/concepts/projects/config/#build-isolation

</details>

## 1/17/2025 (Old Method for magic-pdf 1.x)

<details>
  <summary>Click to expand</summary>

pyproject.toml

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.12.0"

[project.optional-dependencies]
build = ["setuptools", "torch"]
compile = ["detectron2", "magic-pdf[full]==1.0.1"]

[tool.uv]
package = false
prerelease = "allow"
no-build-isolation-package = ["detectron2"]

[tool.uv.sources]
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "main" }
```

Now I just need install by

```sh
uv sync --extra=build
uv sync --extra=build --extra=compile
```
</details>

## 12/27/2024 (Old Method for magic-pdf 1.x)

<details>
  <summary>Click to expand</summary>

pyproject.toml

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
  "detectron2",
  "magic-pdf[full]==1.0.1"
]

[tool.uv]
package = false
prerelease = "allow"

[tool.uv.sources]
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "main" }
```

Then you can install by

```sh
uv venv
uv pip install torch
uv pip install --no-build-isolation git+https://github.com/facebookresearch/detectron2.git
uv sync --dev
```
</details>

**Comment by Zelzahn** [comment]
Thanks for this post! In addition, I had to install `python3.12-dev` (via `apt`) to successfully compile `detectron2` on Ubuntu.

**Comment by JustinTzeJi** [comment]
For Mac:
```toml
[project]
name = "my-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "detectron2",
    "magic-pdf[full]>=1.1.0",
    "torch==2.3.1",
]

[tool.uv]
prerelease = "allow"

[tool.uv.sources]
detectron2 = { url = "https://gcore.jsdelivr.net/gh/myhloli/wheels@main/assets/whl/detectron2/detectron2-0.6-cp310-cp310-macosx_11_0_arm64.whl" }
```

**Comment by ilkersigirci** [comment]
For anyone who want to use `MinerU` with the `paddle-paddle-gpu==u==3.0.0b1` and custom `detectron2` build, you can the following

Install with
```bash
uv sync
uv sync --extra=paddlepaddle-gpu
```

```toml
[project]
name = "workspace"
version = "0.0.1"
requires-python = ">=3.12,<3.13"

dependencies = [
    "detectron2==0.6+2a420edpt2.6.0cu124",
    "magic-pdf[full]>=1.1.0",
]

[project.optional-dependencies]
paddlepaddle-gpu = [
  "paddlepaddle-gpu==3.0.0b1",
]

[tool.uv]
package = false
prerelease = "allow"

[tool.uv.sources]
detectron2 = { index = "miropsota_detectron2" }
paddlepaddle-gpu = { index = "paddlepaddle-gpu" }

[[tool.uv.index]]
name = "paddlepaddle-gpu"
url = "https://www.paddlepaddle.org.cn/packages/stable/cu118"
explicit = true

[[tool.uv.index]]
name = "miropsota_detectron2"
url = "https://miropsota.github.io/torch_packages_builder"
explicit = true
```
